### ISSUE TITLE
Doesn't work well with bundler

### ISSUE THREAD

**Issue by mars-lan** [lumigo-io/opentelemetry-js-distro#239]
**Describe the bug**

https://github.com/lumigo-io/opentelemetry-js-distro/blob/34a919965cae3bf54850302973383e9b6c1c39b5/src/bootstrap.ts#L84 assumes a non-bundled environment where Lumigo's `package.json` file is readily available. This doesn't work when using a bundler like esbuild:

```
@lumigo/opentelemetry An error occurred while initializing the Lumigo OpenTelemetry Distro: no telemetry will be collected and sent to Lumigo. Error: Cannot find module '/package.json'
--
  | 2023-09-29T04:06:18.838-07:00 | Require stack:
  | 2023-09-29T04:06:18.838-07:00 | - /app/usage.js
  | 2023-09-29T04:06:18.838-07:00 | at Function.Module._resolveFilename (node:internal/modules/cjs/loader:1077:15)
  | 2023-09-29T04:06:18.838-07:00 | at Function.Module._load (node:internal/modules/cjs/loader:922:27)
  | 2023-09-29T04:06:18.838-07:00 | at Module.require (node:internal/modules/cjs/loader:1143:19)
  | 2023-09-29T04:06:18.838-07:00 | at require (node:internal/modules/cjs/helpers:119:18)
  | 2023-09-29T04:06:18.838-07:00 | at /node_modules/@lumigo/opentelemetry/src/bootstrap.ts:85:7
  | 2023-09-29T04:06:18.838-07:00 | at Generator.next (<anonymous>)
  | 2023-09-29T04:06:18.838-07:00 | at /app/usage.js:308812:71
  | 2023-09-29T04:06:18.838-07:00 | at new Promise (<anonymous>)
  | 2023-09-29T04:06:18.838-07:00 | at __awaiter (/app/usage.js:308794:14)
  | 2023-09-29T04:06:18.838-07:00 | at init2 (/node_modules/@lumigo/opentelemetry/src/bootstrap.ts:65:66) {
  | 2023-09-29T04:06:18.838-07:00 | code: 'MODULE_NOT_FOUND',
  | 2023-09-29T04:06:18.838-07:00 | requireStack: [ '/app/usage.js' ]
  | 2023-09-29T04:06:18.838-07:00 | }
  | 2023-09-29T04:06:18.842-07:00 | Error: Cannot find module '/package.json'
```

Please either fix the code or add explicit instructions on bundling.

**Comment by tomporat247** [comment]
I encountered a similar issue (using version 1.39.0).
I get the following error:
>@lumigo/opentelemetry An error occurred while initializing the Lumigo OpenTelemetry Distro: no telemetry will be collected and sent to Lumigo. Error: Cannot find module '/usr/app/services/package.json'
    at webpackEmptyContext (webpack://env0/node_modules/.pnpm/@lumigo+opentelemetry@1.39.0/node_modules/@lumigo/opentelemetry/dist/src/%20sync:2:1)
    at <anonymous> (/usr/src/build_cryptographic_materials_cache_key_helpers.ts:86:2)
    at Generator.next (<anonymous>)
    at <anonymous> (/usr/src/build_cryptographic_materials_cache_key_helpers.ts:86:2)
    at new Promise (<anonymous>)
    at exports.modules.855500.__awaiter (/usr/src/build_cryptographic_materials_cache_key_helpers.ts:86:2)
    at init (/usr/src/build_cryptographic_materials_cache_key_helpers.ts:86:2)
    at <anonymous> (/usr/src/build_cryptographic_materials_cache_key_helpers.ts:86:2)
    at Object.445252 (/usr/src/build_cryptographic_materials_cache_key_helpers.ts:86:2)
    at __webpack_require__ (webpack://env0/deployment-service/webpack/bootstrap:19:1) {
  code: 'MODULE_NOT_FOUND'
}

A solution to this might be changing the `||` statements [here](https://github.com/lumigo-io/opentelemetry-js-distro/blob/d3930631281af19752a643c8670ed84520fecabf/src/bootstrap.ts#L92-L95) to actual `try/catch`.

**Comment by tomporat247** [comment]
I encountered a similar issue (using version 1.39.0).
I get the following error:
>@lumigo/opentelemetry An error occurred while initializing the Lumigo OpenTelemetry Distro: no telemetry will be collected and sent to Lumigo. Error: Cannot find module '/usr/app/services/package.json'
    at webpackEmptyContext (webpack://env0/node_modules/.pnpm/@lumigo+opentelemetry@1.39.0/node_modules/@lumigo/opentelemetry/dist/src/%20sync:2:1)
    at <anonymous> (/usr/src/build_cryptographic_materials_cache_key_helpers.ts:86:2)
    at Generator.next (<anonymous>)
    at <anonymous> (/usr/src/build_cryptographic_materials_cache_key_helpers.ts:86:2)
    at new Promise (<anonymous>)
    at exports.modules.855500.__awaiter (/usr/src/build_cryptographic_materials_cache_key_helpers.ts:86:2)
    at init (/usr/src/build_cryptographic_materials_cache_key_helpers.ts:86:2)
    at <anonymous> (/usr/src/build_cryptographic_materials_cache_key_helpers.ts:86:2)
    at Object.445252 (/usr/src/build_cryptographic_materials_cache_key_helpers.ts:86:2)
    at __webpack_require__ (webpack://env0/deployment-service/webpack/bootstrap:19:1) {
  code: 'MODULE_NOT_FOUND'
}

It fails when I define the `@lumigo/opentelemetry` as a `webpack` external and it also fails when I don't define it as such.

A solution to this might be changing the `||` statements [here](https://github.com/lumigo-io/opentelemetry-js-distro/blob/d3930631281af19752a643c8670ed84520fecabf/src/bootstrap.ts#L92-L95) to actual `try/catch`.
